### ISSUE TITLE
Aorus 17g - UK Keys

### ISSUE THREAD

**Issue by jowan** [rcassani/keyboard-fusion-rgb#3]
Hi, thanks for this - still works great, Ubuntu 20.04+ python 3.8.10.

I am using it on an Aorus 17G (YD) in the UK, so the product ID and mapping is very slightly different.

I know there is a more flexible way to do it, like adding config options, but here is a patch to swap the pid and mapping for anyone who wants to use it. I have tried OpenRGB and even though the upcoming 1.0 says it supports it, I've compiled it and it doesn't work. This does ! so thanks again :)

[Aorus-17G-UK.txt](https://github.com/rcassani/keyboard-fusion-rgb/files/14001084/Aorus-17G-UK.txt)

**Comment by rcassani** [comment]
Hi @jowan, thank you very much for the info. The repo is now updated to:

* Accept different `vendor_id` and `product_id` (Commit 3b30be6ef564d82eff67874fe81bb279381d3ce1)
* Support for UK keys: layout `eng_uk` (Commit c610b96196178adc900fcde00aed6467fcab1e08)
